In [1]:
library(tidyverse)
library(limma)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
counts_df <- read_tsv("/mnt/d/gene_expression_example_data/microarray_endometriosis_counts.tsv")
coldata_df <- read_tsv("/mnt/d/gene_expression_example_data/microarray_endometriosis_coldata.tsv")
coldata_df <- coldata_df %>%
    mutate(condition = factor(condition, levels = c("normal", "endometriosis")))

Rows: 21407 Columns: 154

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr   (1): symbol
dbl (153): GSM109815, GSM109816, GSM109817, GSM109828, GSM109829, GSM109830,...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 153 Columns: 8

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): sample_name, series, title, condition, endometriosis_stage, phase, ...
dbl (1): batch


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
min_expr <- log2(50)
min_prop <- 0.25

In [4]:
counts_df

      symbol     GSM109815 GSM109816 GSM109817 GSM109828 GSM109829 GSM109830
1     A1BG        5.685566  6.309144  6.558803  5.676761  5.713494  5.651049
2     A1BG-AS1    6.354643  7.025457  7.019929  6.820971  6.986295  7.019873
3     A1CF        6.017202  6.806242  5.876322  6.075240  6.048896  6.123009
4     A2M        10.705147 10.982733 11.381476 11.434625 11.319421 11.669190
5     A2M-AS1     6.193356  6.496668  6.377511  6.072465  5.664001  6.158695
6     A2ML1       5.936272  6.090145  5.661428  5.772800  5.649532  5.542943
7     A2MP1       6.193356  6.532157  5.972719  6.051718  6.131620  6.140529
8     A4GALT      7.399494  7.314846  7.260542  6.702430  7.204924  7.250284
9     A4GNT       6.212988  6.594580  6.254428  6.024918  6.118253  6.123767
10    AA06        5.930863  6.421702  5.644567  5.882695  5.635277  5.650887
11    AAAS        8.307991  8.295803  8.388261  8.010112  8.259921  8.205769
12    AACS        8.109643  8.180358  8.348733  8.734257  8.251885  8.558062
13    AACSP1      3.929684  3.895525  3.964031  3.969474  3.964031  3.966663
14    AADAC       5.236366  5.101236  4.890368  4.884971  5.055932  5.010302
15    AADACL2     3.546353  3.446094  3.429159  3.345847  3.335029  3.329403
16    AADACP1     4.195329  4.233906  4.064708  4.146682  4.332637  4.102171
17    AADAT       8.217651  8.030530  8.061634  7.286179  7.028966  7.569550
18    AAGAB       7.606111  7.503223  8.174740  7.783256  7.460035  7.370318
19    AAK1        8.192892  8.161748  8.759606  9.014288  8.558367  8.440802
20    AAMDC       8.055014  8.116838  8.075008  8.074759  8.066219  7.775633
21    AAMP        8.419181  8.594788  8.573453  8.750085  8.606666  8.527046
22    AANAT       5.177827  5.322801  5.369359  5.098724  4.951757  5.302356
23    AAR2        8.421017  8.401658  8.493604  8.282975  8.303842  8.343030
24    AARS1       9.543901  9.591302  9.893307  9.157779  9.311054  9.447131
25    AARS2       8.067759  8.034381  8.415032  7.888777  7.987126  7.998226
26    AARSD1      7.482547  7.608351  7.940040  7.518850  7.384443  7.532485
27    AASDH       8.052371  7.739719  7.874676  7.876890  8.106847  8.057399
28    AASDHPPT    9.067446  8.290863  8.518945  9.483085  9.170796  9.062673
29    AASS        5.677549  5.341292  6.071552  6.618679  6.546347  6.883874
30    AATBC       5.467827  5.544332  6.018107  5.124621  5.152694  5.087959
⋮     ⋮          ⋮         ⋮         ⋮         ⋮         ⋮         ⋮
21378 ZSCAN26     7.109178  7.076123  7.051512 6.917225   6.514280  6.893605
21379 ZSCAN29     8.216884  7.992500  8.218323 7.802147   7.951540  7.908428
21380 ZSCAN30     8.514174  8.299628  8.170274 8.131456   8.131456  8.089939
21381 ZSCAN31     6.752059  6.447047  6.928313 6.459476   6.427812  6.097731
21382 ZSCAN32     7.677679  7.673058  7.784663 7.648936   7.910495  7.659687
21383 ZSCAN4      5.035509  5.386720  5.037968 4.605544   4.948800  4.896786
21384 ZSCAN5A     5.472202  5.634845  5.873945 5.953466   5.637112  5.560187
21385 ZSCAN9      7.350241  7.180837  7.245642 7.204614   6.994458  7.118120
21386 ZSWIM1      8.202666  8.505625  8.315825 7.974520   7.957436  8.010033
21387 ZSWIM2      3.361498  3.470143  3.548872 3.553998   3.595670  3.445531
21388 ZSWIM3      6.995121  7.495298  7.248044 7.305173   7.116102  7.576682
21389 ZSWIM4      5.525347  5.663543  5.849868 5.199543   5.356806  5.385719
21390 ZSWIM5      6.948925  7.157071  6.963998 6.948925   6.518732  6.656286
21391 ZSWIM6      8.675910  8.588874  8.327364 8.616429   8.437852  8.598143
21392 ZSWIM7      7.759888  7.632400  8.194322 8.574203   8.194539  8.037877
21393 ZSWIM8      9.126002  9.309486  9.507074 9.570115   9.741320  9.607812
21394 ZSWIM8-AS1  7.458065  7.171647  7.106537 7.059145   6.886157  7.038252
21395 ZSWIM9      6.947680  7.083826  7.648701 7.099303   7.497107  7.403204
21396 ZUP1        6.102859  5.964587  6.253542 6.544367   6.542223  6.197361
21397 ZW10        8.313397  7.865162  8.008453 7.957020   8.083095  7.974213
21398 ZWILCH      8.648811  8.088589  9.103367 7.859225   7.721375  7.645658
21399 ZWINT       9.881066  9.122915 10.122005 7.821796   7.842639  7.414592
21400 ZXDA        5.569230  5.623114  5.564317 5.594251   5.624766  5.574619
21401 ZXDB        6.057409  5.680178  5.671394 6.156656   6.134825  6.298885
21402 ZXDC        7.272264  7.477129  7.342225 7.763413   7.754471  7.771071
21403 ZYG11A      5.896223  5.963051  5.816302 5.816189   6.331827  5.990648
21404 ZYG11B      7.953928  7.819311  8.357682 8.419856   7.860623  7.962587
21405 ZYX        10.110586 10.359008 10.440895 9.986121  10.122976 10.791009
21406 ZZEF1       7.695005  7.715166  7.836197 8.193168   8.122933  8.089190
21407 ZZZ3        8.311897  7.564208  8.048883 8.776825   7.966984  8.217494
      GSM109831 GSM150190 GSM150191 ⋯ GSM1256786 GSM1256787 GSM1256788
1      6.095096  6.734897  6.311050 ⋯  5.807815   5.799219   6.019293
2      6.614798  7.162332  7.692469 ⋯  6.700733   6.763380   6.717756
3      6.480756  6.343271  6.492033 ⋯  6.245288   6.031817   5.796515
4     11.679939 11.021458 10.674658 ⋯ 11.147112  11.202096  11.563820
5      5.950787  6.176829  5.792399 ⋯  6.171834   6.317519   6.506197
6      6.006635  5.752719  6.293694 ⋯  5.671488   5.636839   5.811221
7      6.239424  6.046551  6.383859 ⋯  6.038329   6.151578   6.124441
8      7.084704  7.514505  7.745656 ⋯  7.101046   6.920610   6.783544
9      6.236670  6.186598  6.752778 ⋯  6.290891   6.244271   6.052436
10     6.069808  6.140968  6.651462 ⋯  5.617088   5.788808   5.698525
11     8.234084  8.820366  8.841333 ⋯  8.229365   8.258646   8.207903
12     8.491659  8.466856  7.965819 ⋯  8.217413   8.320430   8.131960
13     3.788244  4.091420  4.259403 ⋯  3.954058   3.943550   3.906583
14     4.967961  4.943560  5.209078 ⋯  5.078745   5.009537   4.890094
15     3.333414  3.435472  3.597981 ⋯  3.415586   3.411070   3.360500
16     4.014776  3.706243  3.902163 ⋯  4.097777   4.336108   4.034784
17     7.404541  7.241694  7.323240 ⋯  7.940188   8.180325   7.692343
18     7.430850  7.523908  7.421382 ⋯  7.627439   7.798608   7.694976
19     8.546727  8.891466  8.038107 ⋯  8.660326   8.569440   8.871073
20     7.668705  8.089407  7.903707 ⋯  8.015142   8.095324   7.849528
21     8.770652  8.930768  8.803504 ⋯  8.588618   8.642460   8.534103
22     5.328901  5.282454  5.398886 ⋯  5.172102   5.182058   5.154178
23     8.488098  8.607663  8.597455 ⋯  8.275629   8.363550   8.294449
24     9.384313  9.645456  9.367470 ⋯  9.305289   9.532917   9.438737
25     7.960252  8.267566  8.259086 ⋯  8.073916   8.286057   7.997038
26     7.587459  7.482651  7.239977 ⋯  7.596378   7.567823   7.353357
27     7.765911  7.465083  7.396798 ⋯  8.139716   7.957985   8.001201
28     9.217809  8.334742  7.553641 ⋯  9.084696   8.973662   8.981356
29     6.527621  5.225151  5.784518 ⋯  6.429095   6.580245   6.753786
30     5.179004  5.399913  5.485502 ⋯  5.581113   5.067504   5.455951
⋮     ⋮         ⋮         ⋮         ⋱ ⋮          ⋮          ⋮
21378  7.154439  6.689024  6.785045 ⋯  7.080316   7.134560   7.045651
21379  7.629679  7.624531  7.432917 ⋯  7.986879   8.067580   8.011093
21380  8.139856  8.262416  8.120504 ⋯  8.429097   8.437103   8.367128
21381  6.703945  6.504409  6.429966 ⋯  6.819994   6.281158   6.632060
21382  7.842288  7.320940  7.257361 ⋯  7.712568   7.866793   7.802085
21383  5.263727  5.002233  5.365453 ⋯  4.774163   4.884699   5.094060
21384  6.087788  5.702647  6.169688 ⋯  5.603089   5.565921   5.606723
21385  7.106800  6.872518  6.835312 ⋯  7.191438   7.219929   7.278219
21386  8.246556  8.474213  8.840692 ⋯  8.163252   8.050695   8.082194
21387  3.476423  3.585297  3.623366 ⋯  3.410362   3.470615   3.454156
21388  7.135233  7.155537  7.417448 ⋯  7.139732   7.237429   7.298975
21389  5.567231  5.806333  6.427823 ⋯  5.549182   5.508122   5.407960
21390  6.948925  6.897496  7.263412 ⋯  6.911552   6.760722   7.272697
21391  8.523862  7.971424  7.785754 ⋯  8.605190   8.606448   8.683372
21392  8.278743  8.147384  7.490883 ⋯  8.359025   8.182006   7.966536
21393  9.584670  9.793728  9.668450 ⋯  9.399047   9.682068   9.658759
21394  7.374351  7.202844  7.629388 ⋯  7.224682   7.197556   7.351966
21395  6.988004  7.671347  7.822888 ⋯  7.185195   7.159288   6.993037
21396  6.309947  5.765030  5.385109 ⋯  6.376304   6.407025   6.324388
21397  8.052676  7.728957  7.776226 ⋯  8.087542   8.092010   8.033841
21398  7.652648  8.141406  7.354612 ⋯  8.429574   8.564270   8.093513
21399  7.468962  9.559818  7.978119 ⋯  9.152311   9.818276   7.915724
21400  5.579764  5.168726  5.183906 ⋯  5.594935   5.622950   5.605820
21401  5.838733  5.897716  5.174408 ⋯  5.997602   6.164834   6.005104
21402  7.508499  7.522286  7.363451 ⋯  7.686328   7.674030   7.781673
21403  5.990648  5.985147  6.172638 ⋯  5.937042   5.867404   5.882119
21404  8.031315  8.291714  7.783332 ⋯  8.336214   8.311109   8.311155
21405 10.945596 11.130939 10.951452 ⋯ 10.244438  10.337396  10.643108
21406  8.007628  7.800383  7.488816 ⋯  7.841115   8.161412   7.970211
21407  8.219092  8.060108  7.393353 ⋯  8.436745   8.311800   8.285576
      GSM1256791 GSM1256793 GSM1256796 GSM1256797 GSM1256798 GSM1256799
1      5.726396   5.767185   5.945817   5.736468   5.966595   5.868001
2      6.878098   6.691541   6.742213   6.825399   6.669743   6.579118
3      6.262572   6.067918   6.291459   5.939247   6.274130   6.093899
4     11.578159  11.268654  11.595849  11.414081  11.245570  11.330142
5      5.722692   6.196140   6.186685   6.062160   6.451924   6.235170
6      5.782499   5.628093   5.671767   5.643708   5.561749   5.711164
7      6.200450   6.225230   6.266043   5.956293   6.194836   6.257100
8      7.082056   7.143511   7.054332   6.971775   6.935188   7.100574
9      6.181848   6.126513   6.163117   6.266918   6.129302   6.278243
10     5.776924   5.636527   5.675551   5.688569   5.665631   5.729384
11     8.205826   8.213173   8.235980   8.227298   8.250370   8.157834
12     8.418783   8.292840   8.393871   8.353918   8.238254   8.229242
13     3.968692   3.966190   3.950861   3.934431   3.925559   3.919438
14     4.888148   5.055151   5.003970   4.866412   4.895702   5.000429
15     3.369048   3.457685   3.398321   3.360378   3.416974   3.390531
16     4.049312   4.102110   4.118990   3.992807   4.148681   4.223856
17     7.089688   7.806189   7.871137   7.337827   7.798366   7.876042
18     7.541782   7.777591   7.814199   7.452814   7.767954   7.823631
19     8.605785   8.599291   8.552571   8.706502   8.773155   8.636811
20     7.792424   7.979048   7.998158   7.730851   7.941071   7.884302
21     8.603463   8.566275   8.619730   8.616782   8.579300   8.535335
22     5.317361   5.134467   5.302102   5.193568   5.269546   5.200621
23     8.346789   8.327524   8.318136   8.328409   8.319051   8.284370
24     9.211815   9.652945   9.608065   9.359684   9.563467   9.483891
25     7.775128   8.002432   7.973310   7.872611   7.973536   7.961731
26     7.416297   7.549254   7.535162   7.297368   7.524277   7.540564
27     7.972583   8.046983   7.994483   7.975802   8.016584   7.974576
28     9.157556   8.984977   8.979785   8.953116   9.077145   9.066577
29     7.390930   6.094190   6.088761   7.146534   6.177832   6.003490
30     5.187682   5.502254   5.312841   5.560029   5.536877   5.326523
⋮     ⋮          ⋮          ⋮          ⋮          ⋮          ⋮
21378  6.801341   6.955624   7.070694   6.916064   7.036456   7.003033
21379  7.851925   8.019541   8.080516   7.946751   8.021674   8.024990
21380  8.071606   8.367614   8.308029   8.273988   8.323244   8.198370
21381  6.375794   6.836454   6.527382   6.371659   6.711515   6.755353
21382  7.654817   7.742425   7.797797   7.720279   7.730294   7.733528
21383  5.023318   4.967080   4.950515   4.941158   5.010521   5.058632
21384  5.623692   5.621128   5.583850   5.708052   5.682045   5.664573
21385  7.224951   7.240773   7.228434   7.189368   7.230840   7.143566
21386  8.165714   8.082175   8.059636   8.152887   8.137897   8.100938
21387  3.558416   3.492538   3.508820   3.512196   3.503506   3.529387
21388  7.795503   7.111404   7.207178   7.581998   7.199059   7.083684
21389  5.245082   5.399053   5.236490   5.413202   5.268573   5.297956
21390  6.732723   6.872689   6.786268   6.883714   7.030225   6.829774
21391  8.616628   8.632331   8.617325   8.557956   8.638883   8.668491
21392  7.931545   8.420097   8.184568   7.777238   8.251161   8.345311
21393  9.410604   9.402811   9.442414   9.735420   9.434932   9.482600
21394  7.160141   7.302821   7.324711   7.066575   7.426920   7.428514
21395  7.029925   7.069223   7.015844   7.030557   7.020711   7.078289
21396  6.241042   6.405423   6.352117   6.310518   6.349230   6.332128
21397  8.064024   8.172392   8.090223   8.133668   8.057529   8.142363
21398  7.845397   8.557240   8.315789   7.895053   8.599608   8.500448
21399  7.661309   9.779680   8.969828   7.449453   9.634942   9.531451
21400  5.596262   5.601890   5.598776   5.594000   5.616071   5.604205
21401  5.971441   5.870772   5.994235   5.893234   5.978539   5.950785
21402  7.566040   7.546095   7.532527   7.857553   7.597493   7.816729
21403  5.946743   5.960328   5.966710   5.984837   6.071701   6.089232
21404  8.055209   8.331800   8.282842   8.096207   8.371499   8.309326
21405 10.509105  10.337931  10.408817  10.591364  10.329832  10.363148
21406  7.936386   7.847303   7.833776   8.204047   7.786818   7.805458
21407  8.128172   8.391327   8.316099   8.252710   8.372052   8.412864
      GSM1256800
1      5.931074
2      6.651996
3      5.928299
4     11.243454
5      5.969264
6      5.600078
7      6.103579
8      7.065269
9      6.216228
10     5.633397
11     8.218571
12     8.369066
13     3.921192
14     4.949976
15     3.380235
16     4.169343
17     8.048110
18     7.741434
19     8.750017
20     8.083049
21     8.589842
22     5.234875
23     8.295284
24     9.481256
25     8.021677
26     7.677662
27     8.018847
28     8.987716
29     6.068689
30     5.804015
⋮     ⋮
21378  6.979172
21379  8.050593
21380  8.249886
21381  6.711402
21382  7.752275
21383  4.994415
21384  5.618431
21385  7.224478
21386  8.147152
21387  3.438279
21388  7.070303
21389  5.466046
21390  6.730076
21391  8.640805
21392  8.220981
21393  9.492176
21394  7.377418
21395  6.906418
21396  6.350462
21397  8.156299
21398  8.469389
21399  9.457855
21400  5.604691
21401  6.003553
21402  7.647706
21403  5.922221
21404  8.257878
21405 10.364964
21406  7.928791
21407  8.247264

In [5]:
filt_counts_df <- counts_df %>%
    filter(rowSums(.[-1] > min_expr) / (ncol(.) - 1) >= min_prop)
filt_expr <- filt_counts_df %>%
    column_to_rownames("symbol") %>%
    as.matrix()

In [6]:
filt_expr

           GSM109815 GSM109816 GSM109817 GSM109828 GSM109829 GSM109830
A1BG        5.685566  6.309144  6.558803  5.676761  5.713494  5.651049
A1BG-AS1    6.354643  7.025457  7.019929  6.820971  6.986295  7.019873
A1CF        6.017202  6.806242  5.876322  6.075240  6.048896  6.123009
A2M        10.705147 10.982733 11.381476 11.434625 11.319421 11.669190
A2M-AS1     6.193356  6.496668  6.377511  6.072465  5.664001  6.158695
A2ML1       5.936272  6.090145  5.661428  5.772800  5.649532  5.542943
A2MP1       6.193356  6.532157  5.972719  6.051718  6.131620  6.140529
A4GALT      7.399494  7.314846  7.260542  6.702430  7.204924  7.250284
A4GNT       6.212988  6.594580  6.254428  6.024918  6.118253  6.123767
AA06        5.930863  6.421702  5.644567  5.882695  5.635277  5.650887
AAAS        8.307991  8.295803  8.388261  8.010112  8.259921  8.205769
AACS        8.109643  8.180358  8.348733  8.734257  8.251885  8.558062
AADAT       8.217651  8.030530  8.061634  7.286179  7.028966  7.569550
AAGAB       7.606111  7.503223  8.174740  7.783256  7.460035  7.370318
AAK1        8.192892  8.161748  8.759606  9.014288  8.558367  8.440802
AAMDC       8.055014  8.116838  8.075008  8.074759  8.066219  7.775633
AAMP        8.419181  8.594788  8.573453  8.750085  8.606666  8.527046
AAR2        8.421017  8.401658  8.493604  8.282975  8.303842  8.343030
AARS1       9.543901  9.591302  9.893307  9.157779  9.311054  9.447131
AARS2       8.067759  8.034381  8.415032  7.888777  7.987126  7.998226
AARSD1      7.482547  7.608351  7.940040  7.518850  7.384443  7.532485
AASDH       8.052371  7.739719  7.874676  7.876890  8.106847  8.057399
AASDHPPT    9.067446  8.290863  8.518945  9.483085  9.170796  9.062673
AASS        5.677549  5.341292  6.071552  6.618679  6.546347  6.883874
AATF        8.266937  8.016332  8.411467  8.389068  8.162360  8.147782
AATK        8.417531  8.332303  8.300006  8.073955  8.060365  8.116944
ABAT        6.852083  6.408962  6.620237  8.285361  8.777261  9.589961
ABCA1       8.487574  7.667627  8.521644  9.458470  9.558792  9.781293
ABCA11P     6.039189  5.743332  5.700547  5.935275  5.983925  5.770753
ABCA2       7.289569  7.179555  7.376582  7.054223  7.572605  7.564456
⋮          ⋮         ⋮         ⋮         ⋮         ⋮         ⋮
ZSCAN22     6.406360  6.452970  6.310014 6.389927   6.614696  6.329696
ZSCAN23     5.652618  5.822972  5.614203 5.538646   5.607309  5.737048
ZSCAN25     7.145459  7.298909  7.315220 7.315220   7.312755  7.506341
ZSCAN26     7.109178  7.076123  7.051512 6.917225   6.514280  6.893605
ZSCAN29     8.216884  7.992500  8.218323 7.802147   7.951540  7.908428
ZSCAN30     8.514174  8.299628  8.170274 8.131456   8.131456  8.089939
ZSCAN31     6.752059  6.447047  6.928313 6.459476   6.427812  6.097731
ZSCAN32     7.677679  7.673058  7.784663 7.648936   7.910495  7.659687
ZSCAN5A     5.472202  5.634845  5.873945 5.953466   5.637112  5.560187
ZSCAN9      7.350241  7.180837  7.245642 7.204614   6.994458  7.118120
ZSWIM1      8.202666  8.505625  8.315825 7.974520   7.957436  8.010033
ZSWIM3      6.995121  7.495298  7.248044 7.305173   7.116102  7.576682
ZSWIM4      5.525347  5.663543  5.849868 5.199543   5.356806  5.385719
ZSWIM5      6.948925  7.157071  6.963998 6.948925   6.518732  6.656286
ZSWIM6      8.675910  8.588874  8.327364 8.616429   8.437852  8.598143
ZSWIM7      7.759888  7.632400  8.194322 8.574203   8.194539  8.037877
ZSWIM8      9.126002  9.309486  9.507074 9.570115   9.741320  9.607812
ZSWIM8-AS1  7.458065  7.171647  7.106537 7.059145   6.886157  7.038252
ZSWIM9      6.947680  7.083826  7.648701 7.099303   7.497107  7.403204
ZUP1        6.102859  5.964587  6.253542 6.544367   6.542223  6.197361
ZW10        8.313397  7.865162  8.008453 7.957020   8.083095  7.974213
ZWILCH      8.648811  8.088589  9.103367 7.859225   7.721375  7.645658
ZWINT       9.881066  9.122915 10.122005 7.821796   7.842639  7.414592
ZXDB        6.057409  5.680178  5.671394 6.156656   6.134825  6.298885
ZXDC        7.272264  7.477129  7.342225 7.763413   7.754471  7.771071
ZYG11A      5.896223  5.963051  5.816302 5.816189   6.331827  5.990648
ZYG11B      7.953928  7.819311  8.357682 8.419856   7.860623  7.962587
ZYX        10.110586 10.359008 10.440895 9.986121  10.122976 10.791009
ZZEF1       7.695005  7.715166  7.836197 8.193168   8.122933  8.089190
ZZZ3        8.311897  7.564208  8.048883 8.776825   7.966984  8.217494
           GSM109831 GSM150190 GSM150191 GSM150192 ⋯ GSM1256786 GSM1256787
A1BG        6.095096  6.734897  6.311050  6.201764 ⋯  5.807815   5.799219
A1BG-AS1    6.614798  7.162332  7.692469  7.116755 ⋯  6.700733   6.763380
A1CF        6.480756  6.343271  6.492033  6.303324 ⋯  6.245288   6.031817
A2M        11.679939 11.021458 10.674658 11.074659 ⋯ 11.147112  11.202096
A2M-AS1     5.950787  6.176829  5.792399  6.005239 ⋯  6.171834   6.317519
A2ML1       6.006635  5.752719  6.293694  5.755191 ⋯  5.671488   5.636839
A2MP1       6.239424  6.046551  6.383859  6.206954 ⋯  6.038329   6.151578
A4GALT      7.084704  7.514505  7.745656  7.672225 ⋯  7.101046   6.920610
A4GNT       6.236670  6.186598  6.752778  6.268343 ⋯  6.290891   6.244271
AA06        6.069808  6.140968  6.651462  6.054905 ⋯  5.617088   5.788808
AAAS        8.234084  8.820366  8.841333  8.795422 ⋯  8.229365   8.258646
AACS        8.491659  8.466856  7.965819  8.654117 ⋯  8.217413   8.320430
AADAT       7.404541  7.241694  7.323240  7.344661 ⋯  7.940188   8.180325
AAGAB       7.430850  7.523908  7.421382  7.423270 ⋯  7.627439   7.798608
AAK1        8.546727  8.891466  8.038107  8.619330 ⋯  8.660326   8.569440
AAMDC       7.668705  8.089407  7.903707  8.163455 ⋯  8.015142   8.095324
AAMP        8.770652  8.930768  8.803504  8.916311 ⋯  8.588618   8.642460
AAR2        8.488098  8.607663  8.597455  8.596213 ⋯  8.275629   8.363550
AARS1       9.384313  9.645456  9.367470  9.550783 ⋯  9.305289   9.532917
AARS2       7.960252  8.267566  8.259086  8.237361 ⋯  8.073916   8.286057
AARSD1      7.587459  7.482651  7.239977  7.436509 ⋯  7.596378   7.567823
AASDH       7.765911  7.465083  7.396798  7.328128 ⋯  8.139716   7.957985
AASDHPPT    9.217809  8.334742  7.553641  8.360009 ⋯  9.084696   8.973662
AASS        6.527621  5.225151  5.784518  5.670313 ⋯  6.429095   6.580245
AATF        8.040122  8.432260  8.081312  8.155832 ⋯  8.102016   8.269262
AATK        8.277601  8.685570  8.954631  8.631418 ⋯  8.111804   8.173727
ABAT        8.417160  5.981711  6.107601  6.150126 ⋯  7.187966   8.126208
ABCA1       9.250193  7.897196  8.518194  7.589570 ⋯  8.730001   8.745485
ABCA11P     5.844288  5.551566  5.261366  5.562964 ⋯  5.975942   5.955402
ABCA2       7.596348  7.914438  7.696824  7.686664 ⋯  7.384488   7.426671
⋮          ⋮         ⋮         ⋮         ⋮         ⋱ ⋮          ⋮
ZSCAN22     6.745825  6.167395  6.733304  6.307867 ⋯  6.413810   6.449122
ZSCAN23     5.603222  5.551248  5.784311  5.572322 ⋯  5.814897   5.619659
ZSCAN25     7.471084  7.289895  7.501204  7.278746 ⋯  7.357725   7.446825
ZSCAN26     7.154439  6.689024  6.785045  6.640260 ⋯  7.080316   7.134560
ZSCAN29     7.629679  7.624531  7.432917  7.517858 ⋯  7.986879   8.067580
ZSCAN30     8.139856  8.262416  8.120504  8.015751 ⋯  8.429097   8.437103
ZSCAN31     6.703945  6.504409  6.429966  6.442807 ⋯  6.819994   6.281158
ZSCAN32     7.842288  7.320940  7.257361  7.301667 ⋯  7.712568   7.866793
ZSCAN5A     6.087788  5.702647  6.169688  5.930574 ⋯  5.603089   5.565921
ZSCAN9      7.106800  6.872518  6.835312  6.720625 ⋯  7.191438   7.219929
ZSWIM1      8.246556  8.474213  8.840692  8.446637 ⋯  8.163252   8.050695
ZSWIM3      7.135233  7.155537  7.417448  7.267199 ⋯  7.139732   7.237429
ZSWIM4      5.567231  5.806333  6.427823  5.754422 ⋯  5.549182   5.508122
ZSWIM5      6.948925  6.897496  7.263412  6.988915 ⋯  6.911552   6.760722
ZSWIM6      8.523862  7.971424  7.785754  7.977563 ⋯  8.605190   8.606448
ZSWIM7      8.278743  8.147384  7.490883  7.778888 ⋯  8.359025   8.182006
ZSWIM8      9.584670  9.793728  9.668450  9.687187 ⋯  9.399047   9.682068
ZSWIM8-AS1  7.374351  7.202844  7.629388  7.067219 ⋯  7.224682   7.197556
ZSWIM9      6.988004  7.671347  7.822888  7.655340 ⋯  7.185195   7.159288
ZUP1        6.309947  5.765030  5.385109  5.656473 ⋯  6.376304   6.407025
ZW10        8.052676  7.728957  7.776226  7.654227 ⋯  8.087542   8.092010
ZWILCH      7.652648  8.141406  7.354612  7.887031 ⋯  8.429574   8.564270
ZWINT       7.468962  9.559818  7.978119  9.214052 ⋯  9.152311   9.818276
ZXDB        5.838733  5.897716  5.174408  5.873457 ⋯  5.997602   6.164834
ZXDC        7.508499  7.522286  7.363451  7.435199 ⋯  7.686328   7.674030
ZYG11A      5.990648  5.985147  6.172638  6.242158 ⋯  5.937042   5.867404
ZYG11B      8.031315  8.291714  7.783332  8.016974 ⋯  8.336214   8.311109
ZYX        10.945596 11.130939 10.951452 10.866998 ⋯ 10.244438  10.337396
ZZEF1       8.007628  7.800383  7.488816  7.766272 ⋯  7.841115   8.161412
ZZZ3        8.219092  8.060108  7.393353  7.932835 ⋯  8.436745   8.311800
           GSM1256788 GSM1256791 GSM1256793 GSM1256796 GSM1256797 GSM1256798
A1BG        6.019293   5.726396   5.767185   5.945817   5.736468   5.966595
A1BG-AS1    6.717756   6.878098   6.691541   6.742213   6.825399   6.669743
A1CF        5.796515   6.262572   6.067918   6.291459   5.939247   6.274130
A2M        11.563820  11.578159  11.268654  11.595849  11.414081  11.245570
A2M-AS1     6.506197   5.722692   6.196140   6.186685   6.062160   6.451924
A2ML1       5.811221   5.782499   5.628093   5.671767   5.643708   5.561749
A2MP1       6.124441   6.200450   6.225230   6.266043   5.956293   6.194836
A4GALT      6.783544   7.082056   7.143511   7.054332   6.971775   6.935188
A4GNT       6.052436   6.181848   6.126513   6.163117   6.266918   6.129302
AA06        5.698525   5.776924   5.636527   5.675551   5.688569   5.665631
AAAS        8.207903   8.205826   8.213173   8.235980   8.227298   8.250370
AACS        8.131960   8.418783   8.292840   8.393871   8.353918   8.238254
AADAT       7.692343   7.089688   7.806189   7.871137   7.337827   7.798366
AAGAB       7.694976   7.541782   7.777591   7.814199   7.452814   7.767954
AAK1        8.871073   8.605785   8.599291   8.552571   8.706502   8.773155
AAMDC       7.849528   7.792424   7.979048   7.998158   7.730851   7.941071
AAMP        8.534103   8.603463   8.566275   8.619730   8.616782   8.579300
AAR2        8.294449   8.346789   8.327524   8.318136   8.328409   8.319051
AARS1       9.438737   9.211815   9.652945   9.608065   9.359684   9.563467
AARS2       7.997038   7.775128   8.002432   7.973310   7.872611   7.973536
AARSD1      7.353357   7.416297   7.549254   7.535162   7.297368   7.524277
AASDH       8.001201   7.972583   8.046983   7.994483   7.975802   8.016584
AASDHPPT    8.981356   9.157556   8.984977   8.979785   8.953116   9.077145
AASS        6.753786   7.390930   6.094190   6.088761   7.146534   6.177832
AATF        8.207243   8.163470   8.150715   8.254071   8.203181   8.093464
AATK        8.143471   8.250768   8.125425   8.170730   8.206236   8.198625
ABAT        7.118893   9.041681   7.307359   6.944654   9.279527   6.965166
ABCA1       9.975274   9.694891   8.208221   8.530066   9.732941   8.493712
ABCA11P     5.744840   5.757633   5.921126   6.009502   5.720938   5.852531
ABCA2       7.378751   7.245775   7.345990   7.280658   7.219064   7.280393
⋮          ⋮          ⋮          ⋮          ⋮          ⋮          ⋮
ZSCAN22     6.347896   6.443117   6.356243   6.262334   6.359370   6.290525
ZSCAN23     5.736798   5.770997   5.703617   5.721312   5.802678   5.681307
ZSCAN25     7.255647   7.127281   7.333652   7.362924   7.121448   7.383837
ZSCAN26     7.045651   6.801341   6.955624   7.070694   6.916064   7.036456
ZSCAN29     8.011093   7.851925   8.019541   8.080516   7.946751   8.021674
ZSCAN30     8.367128   8.071606   8.367614   8.308029   8.273988   8.323244
ZSCAN31     6.632060   6.375794   6.836454   6.527382   6.371659   6.711515
ZSCAN32     7.802085   7.654817   7.742425   7.797797   7.720279   7.730294
ZSCAN5A     5.606723   5.623692   5.621128   5.583850   5.708052   5.682045
ZSCAN9      7.278219   7.224951   7.240773   7.228434   7.189368   7.230840
ZSWIM1      8.082194   8.165714   8.082175   8.059636   8.152887   8.137897
ZSWIM3      7.298975   7.795503   7.111404   7.207178   7.581998   7.199059
ZSWIM4      5.407960   5.245082   5.399053   5.236490   5.413202   5.268573
ZSWIM5      7.272697   6.732723   6.872689   6.786268   6.883714   7.030225
ZSWIM6      8.683372   8.616628   8.632331   8.617325   8.557956   8.638883
ZSWIM7      7.966536   7.931545   8.420097   8.184568   7.777238   8.251161
ZSWIM8      9.658759   9.410604   9.402811   9.442414   9.735420   9.434932
ZSWIM8-AS1  7.351966   7.160141   7.302821   7.324711   7.066575   7.426920
ZSWIM9      6.993037   7.029925   7.069223   7.015844   7.030557   7.020711
ZUP1        6.324388   6.241042   6.405423   6.352117   6.310518   6.349230
ZW10        8.033841   8.064024   8.172392   8.090223   8.133668   8.057529
ZWILCH      8.093513   7.845397   8.557240   8.315789   7.895053   8.599608
ZWINT       7.915724   7.661309   9.779680   8.969828   7.449453   9.634942
ZXDB        6.005104   5.971441   5.870772   5.994235   5.893234   5.978539
ZXDC        7.781673   7.566040   7.546095   7.532527   7.857553   7.597493
ZYG11A      5.882119   5.946743   5.960328   5.966710   5.984837   6.071701
ZYG11B      8.311155   8.055209   8.331800   8.282842   8.096207   8.371499
ZYX        10.643108  10.509105  10.337931  10.408817  10.591364  10.329832
ZZEF1       7.970211   7.936386   7.847303   7.833776   8.204047   7.786818
ZZZ3        8.285576   8.128172   8.391327   8.316099   8.252710   8.372052
           GSM1256799 GSM1256800
A1BG        5.868001   5.931074
A1BG-AS1    6.579118   6.651996
A1CF        6.093899   5.928299
A2M        11.330142  11.243454
A2M-AS1     6.235170   5.969264
A2ML1       5.711164   5.600078
A2MP1       6.257100   6.103579
A4GALT      7.100574   7.065269
A4GNT       6.278243   6.216228
AA06        5.729384   5.633397
AAAS        8.157834   8.218571
AACS        8.229242   8.369066
AADAT       7.876042   8.048110
AAGAB       7.823631   7.741434
AAK1        8.636811   8.750017
AAMDC       7.884302   8.083049
AAMP        8.535335   8.589842
AAR2        8.284370   8.295284
AARS1       9.483891   9.481256
AARS2       7.961731   8.021677
AARSD1      7.540564   7.677662
AASDH       7.974576   8.018847
AASDHPPT    9.066577   8.987716
AASS        6.003490   6.068689
AATF        8.016139   8.105715
AATK        8.176326   8.222396
ABAT        7.379199   7.474721
ABCA1       8.450087   7.823172
ABCA11P     5.893205   5.790228
ABCA2       7.356718   7.276302
⋮          ⋮          ⋮
ZSCAN22     6.261643   6.327398
ZSCAN23     5.710970   5.771048
ZSCAN25     7.274997   7.339113
ZSCAN26     7.003033   6.979172
ZSCAN29     8.024990   8.050593
ZSCAN30     8.198370   8.249886
ZSCAN31     6.755353   6.711402
ZSCAN32     7.733528   7.752275
ZSCAN5A     5.664573   5.618431
ZSCAN9      7.143566   7.224478
ZSWIM1      8.100938   8.147152
ZSWIM3      7.083684   7.070303
ZSWIM4      5.297956   5.466046
ZSWIM5      6.829774   6.730076
ZSWIM6      8.668491   8.640805
ZSWIM7      8.345311   8.220981
ZSWIM8      9.482600   9.492176
ZSWIM8-AS1  7.428514   7.377418
ZSWIM9      7.078289   6.906418
ZUP1        6.332128   6.350462
ZW10        8.142363   8.156299
ZWILCH      8.500448   8.469389
ZWINT       9.531451   9.457855
ZXDB        5.950785   6.003553
ZXDC        7.816729   7.647706
ZYG11A      6.089232   5.922221
ZYG11B      8.309326   8.257878
ZYX        10.363148  10.364964
ZZEF1       7.805458   7.928791
ZZZ3        8.412864   8.247264

In [7]:
design <- model.matrix(~ condition, data = coldata_df)
rownames(design) <- coldata_df$sample_name

In [8]:
design
all(colnames(filt_expr) == rownames(design))

           (Intercept) conditionendometriosis
GSM109815  1           0
GSM109816  1           0
GSM109817  1           0
GSM109828  1           0
GSM109829  1           0
GSM109830  1           0
GSM109831  1           0
GSM150190  1           1
GSM150191  1           1
GSM150192  1           1
GSM150193  1           1
GSM150194  1           1
GSM150195  1           1
GSM150196  1           0
GSM150197  1           0
GSM150198  1           0
GSM150199  1           0
GSM150201  1           0
GSM150202  1           1
GSM150203  1           1
GSM150204  1           1
GSM150205  1           1
GSM150206  1           1
GSM150207  1           1
GSM150208  1           0
GSM150209  1           0
GSM150210  1           0
GSM150211  1           1
GSM150212  1           1
GSM150213  1           1
⋮          ⋮           ⋮
GSM1256732 1           0
GSM1256733 1           0
GSM1256734 1           0
GSM1256766 1           0
GSM1256767 1           0
GSM1256768 1           0
GSM1256769 1           0
GSM1256770 1           0
GSM1256771 1           0
GSM1256772 1           0
GSM1256774 1           1
GSM1256776 1           1
GSM1256777 1           1
GSM1256778 1           1
GSM1256779 1           1
GSM1256780 1           1
GSM1256781 1           1
GSM1256782 1           1
GSM1256784 1           0
GSM1256785 1           0
GSM1256786 1           0
GSM1256787 1           0
GSM1256788 1           0
GSM1256791 1           0
GSM1256793 1           0
GSM1256796 1           0
GSM1256797 1           0
GSM1256798 1           0
GSM1256799 1           0
GSM1256800 1           0

[1] TRUE

In [9]:
qual_weights <- arrayWeights(filt_expr, design = design)

In [10]:
lm_fit <- lmFit(filt_expr, design = design, weights = qual_weights)
bayes_fit <- eBayes(lm_fit)

In [11]:
bayes_fit$coefficients %>% colnames()

[1] "(Intercept)"            "conditionendometriosis"

In [12]:
fit_de_res_df <- topTable(bayes_fit, coef = "conditionendometriosis", number = nrow(filt_counts_df), adjust.method = "BH") %>%
    rename(lfc = logFC, ave_expr = AveExpr, pval = P.Value, padj = adj.P.Val) %>%
    as_tibble(rownames = "symbol")

In [15]:
2^(0.9797001)

[1] 1.972055

In [13]:
fit_de_res_df

      symbol       lfc           ave_expr  t             pval
1     RBM25        -0.9797001     9.271442 -115.68463    5.281688e-151
2     PRH1          0.5228194     6.565680   99.84267    2.477561e-141
3     PLPP6        -0.8366814     6.691173  -91.11445    2.401855e-135
4     ZBED8        -0.9876665     5.984509  -88.96926    8.642004e-134
5     ZMAT3        -0.7141661     7.014628  -88.67287    1.427071e-133
6     FECH         -0.5544542     7.576011  -88.56792    1.705088e-133
7     FOSB          2.3816607     8.079308   87.88804    5.428193e-133
8     XRN2         -0.8461322     8.257239  -86.54415    5.493155e-132
9     CWC15        -0.6416429     9.325332  -85.44062    3.771230e-131
10    CANX         -0.5132399    11.726288  -85.26527    5.133105e-131
11    SH2B2         0.7482505     9.285093   83.63059    9.364482e-130
12    FIG4         -0.5887239     7.543685  -82.98916    2.970231e-129
13    VPS54        -0.7801367     7.517577  -80.56887    2.502142e-127
14    MOSPD3        0.8125652     8.748491   80.41654    3.321586e-127
15    UBE2K        -0.4791498     9.003606  -79.94491    8.010763e-127
16    HSP90B1      -0.9061631    11.447338  -78.54398    1.127603e-125
17    YDJC          0.7266638     8.327229   78.00467    3.158603e-125
18    ZMYM4        -0.8441405     8.037352  -77.05372    1.974608e-124
19    PDS5A        -0.7312687     8.154638  -75.88843    1.921762e-123
20    MCM9         -0.6976707     6.250771  -75.49055    4.211359e-123
21    FXYD1         1.0773670     8.199324   75.01041    1.091081e-122
22    C11orf68      0.6935014     9.205659   73.84588    1.124881e-121
23    PUS10        -0.5249112     5.371568  -73.51831    2.181987e-121
24    C8orf82       0.6659164     8.700490   72.91201    7.492772e-121
25    RHOG          0.8282023     9.208584   71.66036    9.866843e-120
26    CSNK1A1      -0.6775647    10.308999  -71.37359    1.791730e-119
27    HACL1        -0.6864332     6.070890  -71.07490    3.343314e-119
28    U2SURP       -0.9721989     8.420604  -68.98336    2.829724e-117
29    FOS           2.6664077     7.848969   67.65542    5.061137e-116
30    ZC3H11A      -0.7300084    10.301663  -67.27437    1.169245e-115
⋮     ⋮            ⋮             ⋮         ⋮             ⋮
17139 MRGBP         1.454384e-03  7.025438  4.485139e-02 0.9642842
17140 HOXA6         1.310087e-03  5.902223  4.279324e-02 0.9659221
17141 DNAI2        -1.396452e-03  5.566679 -3.837601e-02 0.9694378
17142 APCDD1       -2.301868e-03 11.709607 -3.710760e-02 0.9704475
17143 SLC28A3       2.047901e-03  6.234259  3.591840e-02 0.9713942
17144 DDOST        -1.262841e-03 11.104200 -3.366775e-02 0.9731859
17145 TMEM165      -2.712915e-03 10.442816 -3.319868e-02 0.9735594
17146 CDCP1        -1.707046e-03  8.082325 -3.250200e-02 0.9741140
17147 GMFG         -1.244332e-03  6.706907 -3.201703e-02 0.9745001
17148 C2orf92      -7.388657e-04  5.619381 -2.867477e-02 0.9771613
17149 PCDHAC1      -5.306352e-04  5.868949 -2.861513e-02 0.9772088
17150 RHOA         -5.574128e-04 11.964440 -2.802350e-02 0.9776799
17151 CD34         -2.156798e-03  8.176119 -2.656349e-02 0.9788425
17152 LOC729732     3.810476e-03  7.230252  2.550495e-02 0.9796854
17153 MGST1        -3.335902e-03 10.843961 -2.474586e-02 0.9802899
17154 EN2           2.145288e-03  6.190054  2.460708e-02 0.9804004
17155 SNORD50A      7.861576e-04  6.900797  2.353782e-02 0.9812519
17156 WARS1         1.181237e-03  9.302858  2.187401e-02 0.9825769
17157 NAV2-AS4      5.126533e-04  6.880661  1.980527e-02 0.9842245
17158 LOC105370478  4.430552e-04  6.012989  1.581236e-02 0.9874047
17159 ZNF474        2.787548e-04  5.882382  1.360743e-02 0.9891609
17160 TRPM6         1.709676e-03  6.800276  1.267053e-02 0.9899071
17161 DMAP1        -3.440063e-04  6.945874 -1.112566e-02 0.9911377
17162 ADAMTS5      -1.837796e-03  8.060863 -9.998215e-03 0.9920357
17163 EDARADD       2.428862e-04  6.212103  9.613299e-03 0.9923423
17164 PRL           3.565267e-04  5.529282  7.212180e-03 0.9942549
17165 MED24        -6.814912e-04  8.314041 -6.191246e-03 0.9950682
17166 SERPINA1     -4.639283e-04  9.369553 -4.150697e-03 0.9966936
17167 COX17         6.685398e-05  8.153105  1.302325e-03 0.9989626
17168 HSBP1L1       1.955765e-07  7.207488  3.827703e-06 0.9999970
      padj          B
1     9.067602e-147 334.9097
2     2.126738e-137 312.9926
3     1.374502e-131 299.3625
4     3.709148e-130 295.8130
5     4.878826e-130 295.3159
6     4.878826e-130 295.1395
7     1.331303e-129 293.9916
8     1.178831e-128 291.6966
9     7.193831e-128 289.7855
10    8.812514e-128 289.4796
11    1.461540e-126 286.5977
12    4.249411e-126 285.4516
13    3.304368e-124 281.0476
14    4.073213e-124 280.7661
15    9.168585e-124 279.8913
16    1.209918e-122 277.2625
17    3.189818e-122 276.2382
18    1.883337e-121 274.4154
19    1.736464e-120 272.1516
20    3.615030e-120 271.3709
21    8.919850e-120 270.4235
22    8.778164e-119 268.1010
23    1.628711e-118 267.4413
24    5.359830e-118 266.2128
25    6.775759e-117 263.6452
26    1.183093e-116 263.0509
27    2.125852e-116 262.4294
28    1.735025e-114 258.0060
29    2.996193e-113 255.1304
30    6.691197e-113 254.2954
⋮     ⋮             ⋮
17139 0.9659158     -8.658989
17140 0.9675000     -8.659080
17141 0.9709649     -8.659260
17142 0.9719194     -8.659308
17143 0.9728108     -8.659352
17144 0.9745483     -8.659431
17145 0.9748654     -8.659446
17146 0.9753639     -8.659469
17147 0.9756936     -8.659485
17148 0.9782915     -8.659587
17149 0.9782915     -8.659589
17150 0.9787060     -8.659606
17151 0.9798127     -8.659646
17152 0.9805993     -8.659674
17153 0.9811471     -8.659693
17154 0.9812005     -8.659696
17155 0.9819955     -8.659722
17156 0.9832642     -8.659760
17157 0.9848555     -8.659804
17158 0.9879801     -8.659875
17159 0.9896797     -8.659908
17160 0.9903686     -8.659920
17161 0.9915420     -8.659939
17162 0.9923825     -8.659951
17163 0.9926314     -8.659954
17164 0.9944867     -8.659975
17165 0.9952421     -8.659982
17166 0.9968098     -8.659992
17167 0.9990208     -8.660000
17168 0.9999970     -8.660001